/* Vishnu Sahasranama --- attribute-graph overlay (Proposal A)
 *
 * Concepts are the divine attributes that the namas predicate. Each concept
 * gathers the namas in data.js that emphasize it; tier groupings provide a
 * top-down browse.
 *
 * Schema per concept:
 *   { id, tier,
 *     en, dev, kn, hi,              -- canonical labels
 *     title: {en,dev,kn,hi},
 *     note:  {en,dev,kn,hi},
 *     nama_ids: ['n_0xxx', ...] }   -- back-link to data.js NODES
 *
 * The bidirectional traversal: each nama in data.js has a tags array, each
 * concept here has a nama_ids array. The viewer maintains both indices.
 */

const CTIERS = [
  { id: "para_tattva", en: "Para-tattva", dev: "पर-तत्त्व", kn: "ಪರ-ತತ್ತ್ವ", hi: "पर-तत्त्व", gloss: "The supreme reality — Hari/Vishnu/Narayana as sarvottama" },
  { id: "svarupa_guna", en: "Svarūpa-guṇa", dev: "स्वरूप-गुण", kn: "ಸ್ವರೂಪ-ಗುಣ", hi: "स्वरूप-गुण", gloss: "Essential attributes — sat, cit, ānanda, jñāna, bala, aiśvarya, vīrya, tejas" },
  { id: "lila_guna", en: "Līlā-guṇa", dev: "लीला-गुण", kn: "ಲೀಲಾ-ಗುಣ", hi: "लीला-गुण", gloss: "Cosmic-play attributes — sṛṣṭi, sthiti, saṃhāra, avatāra" },
  { id: "karunya_guna", en: "Kāruṇya-guṇa", dev: "कारुण्य-गुण", kn: "ಕಾರುಣ್ಯ-ಗುಣ", hi: "कारुण्य-गुण", gloss: "Mercy attributes — vātsalya, akhilāghahāritva, praṇata-rakṣakatva" },
  { id: "yoga_sthana", en: "Yoga-sthāna", dev: "योग-स्थान", kn: "ಯೋಗ-ಸ್ಥಾನ", hi: "योग-स्थान", gloss: "Yogic-station attributes — yogeśvaratva, antaryāmin, sūtrātman, hṛdaya-sthita" },
  { id: "bhakta_sambandha", en: "Bhakta-sambandha", dev: "भक्त-सम्बन्ध", kn: "ಭಕ್ತ-ಸಂಬಂಧ", hi: "भक्त-सम्बन्ध", gloss: "Devotee-relation attributes — bhakta-priya, bhakta-vatsala, aśaraṇya-śaraṇa" },
  { id: "mokshaprada", en: "Mokṣa-prada", dev: "मोक्ष-प्रद", kn: "ಮೋಕ್ಷ-ಪ್ರದ", hi: "मोक्ष-प्रद", gloss: "Liberation-bestowing attributes — mukti-prada, sālokya, sāmīpya, sārūpya, sāyujya" },
];

const CONCEPTS = [
  {
    id: "c_hari_sarvottamatva", tier: "para_tattva",
    en: "Hari-sarvottamatva", dev: "हरि-सर्वोत्तमत्व", kn: "ಹರಿ-ಸರ್ವೋತ್ತಮತ್ವ", hi: "हरि-सर्वोत्तमत्व",
    title: { en: "Hari's absolute supremacy", dev: "हरेः सर्वोत्तमत्वम्", kn: "ಹರಿಯ ಸರ್ವೋತ್ತಮತ್ವ", hi: "हरि की सर्वोत्तमता" },
    note:  { en: "The foundational Madhva axiom: Hari is the highest, no one equal or superior. Every other being - jiva, devata, even Lakshmi - is strictly subordinate. The pancha-bheda system starts here.", dev: "मध्व-सिद्धान्तस्य आधार-शिला: हरिः सर्वोत्कृष्टः, न तस्य समः न अधिकः। सर्वम् इतरत् - जीवाः देवताः लक्ष्मीरपि - तत्-परतन्त्रम्। पञ्च-भेद-व्यवस्था अत एव प्रारभते।", kn: "ಮಧ್ವ-ಸಿದ್ಧಾಂತದ ಆಧಾರ-ಶಿಲೆ: ಹರಿಯು ಸರ್ವೋತ್ಕೃಷ್ಟ, ಅವನಿಗೆ ಸಮಾನನಿಲ್ಲ ಅಧಿಕನಿಲ್ಲ. ಎಲ್ಲ ಇತರ - ಜೀವಗಳು, ದೇವತೆಗಳು, ಲಕ್ಷ್ಮಿಯೂ - ಅವನ ಪರತಂತ್ರ. ಪಂಚ-ಭೇದ-ವ್ಯವಸ್ಥೆ ಇದರಿಂದಲೇ ಪ್ರಾರಂಭ.", hi: "मध्व-सिद्धान्त की आधार-शिला: हरि सर्वोत्कृष्ट हैं, उनके समान या अधिक कोई नहीं। बाकी सब - जीव, देवता, लक्ष्मी भी - उनके परतन्त्र हैं। पञ्च-भेद यहीं से शुरू होता है।" },
    nama_ids: ["n_0001", "n_0012", "n_0024", "n_0049", "n_0245", "n_0337", "n_0552", "n_0591", "n_0650", "n_0656", "n_0659", "n_0702", "n_0991"],
  },
  {
    id: "c_sarva_vyapakatva", tier: "para_tattva",
    en: "Sarva-vyapakatva", dev: "सर्व-व्यापकत्व", kn: "ಸರ್ವ-ವ್ಯಾಪಕತ್ವ", hi: "सर्व-व्यापकत्व",
    title: { en: "All-pervasiveness", dev: "सर्व-व्यापकत्वम्", kn: "ಸರ್ವ-ವ್ಯಾಪಕತ್ವ", hi: "सर्वव्यापकता" },
    note:  { en: "Hari pervades all space, time, and being. The verse-opening Vishvam asserts cosmic scope; Trivikrama's three strides enact the same truth as cosmic gesture.", dev: "हरिः देश-काल-वस्तुषु सर्वत्र व्याप्तः। श्लोक-आरम्भे 'विश्वम्' इति शब्देन सर्व-व्याप्ति-निर्देशः; त्रिविक्रमस्य त्रिभिः पादैः क्रान्तिः तस्यैव कर्म-रूपम्।", kn: "ಹರಿ ದೇಶ-ಕಾಲ-ವಸ್ತುಗಳಲ್ಲಿ ಸರ್ವತ್ರ ವ್ಯಾಪ್ತ. ಶ್ಲೋಕದ ಆರಂಭದಲ್ಲಿ 'ವಿಶ್ವಂ' ಶಬ್ದದಿಂದ ಸರ್ವ-ವ್ಯಾಪ್ತಿ-ನಿರ್ದೇಶ; ತ್ರಿವಿಕ್ರಮನ ಮೂರು ಹೆಜ್ಜೆಗಳ ಆಕ್ರಮಣ ಅದೇ ಸತ್ಯದ ಕರ್ಮ-ರೂಪ.", hi: "हरि देश, काल और वस्तु में सर्वत्र व्याप्त हैं। श्लोक के आरम्भ में 'विश्वं' शब्द से सर्व-व्याप्ति का निर्देश; त्रिविक्रम के तीन पगों से क्रान्ति उसी सत्य की क्रिया-रूप।" },
    nama_ids: ["n_0001", "n_0530"],
  },
  {
    id: "c_antaryamitva", tier: "para_tattva",
    en: "Antaryamitva", dev: "अन्तर्यामित्व", kn: "ಅಂತರ್ಯಾಮಿತ್ವ", hi: "अन्तर्यामित्व",
    title: { en: "Indwelling (the in-dweller-relation)", dev: "अन्तर्यामित्वम्", kn: "ಅಂತರ್ಯಾಮಿತ್ವ", hi: "अन्तर्यामित्व" },
    note:  { en: "Hari dwells inside every being as the inner witness and ordainer. The name Vishnu itself encodes this (visheh - to enter). Madhva makes antaryamitva ontologically distinct from svarupa-aikya - Hari is IN every jiva but never identical with it.", dev: "हरिः प्रत्येक-भूते अन्तर्यामि-रूपेण साक्षि-नियन्तृ-तया वसति। 'विष्णुः' इति नामैव विशि-धातु-मूलं तदर्थम्। मध्व-मते अन्तर्यामित्वं स्वरूप-ऐक्यात् भिन्नम् - हरिः प्रत्येक-जीवे अस्ति, न तु तेन तादात्म्येन।", kn: "ಹರಿ ಪ್ರತಿ ಭೂತದಲ್ಲಿ ಅಂತರ್ಯಾಮಿ-ರೂಪದಿಂದ ಸಾಕ್ಷಿ-ನಿಯಂತೃ-ರೂಪದಲ್ಲಿ ವಾಸಿಸುತ್ತಾನೆ. 'ವಿಷ್ಣು' ಎಂಬ ನಾಮವೇ ವಿಶಿ-ಧಾತು-ಮೂಲ. ಮಧ್ವ-ಮತದಲ್ಲಿ ಅಂತರ್ಯಾಮಿತ್ವ ಸ್ವರೂಪ-ಐಕ್ಯದಿಂದ ಭಿನ್ನ — ಹರಿ ಪ್ರತಿ ಜೀವದಲ್ಲಿ ಇದ್ದಾನೆ, ಆದರೆ ಅದರೊಂದಿಗೆ ತಾದಾತ್ಮ್ಯವಲ್ಲ.", hi: "हरि हर भूत में अन्तर्यामी रूप से साक्षी-नियन्ता के रूप में बसते हैं। 'विष्णु' नाम स्वयं विश्-धातु-मूलक है। मध्व मत में अन्तर्यामित्व स्वरूप-ऐक्य से भिन्न है - हरि हर जीव में हैं पर उसके साथ तादात्म्य नहीं।" },
    nama_ids: ["n_0002", "n_0007", "n_0052", "n_0245"],
  },
  {
    id: "c_jiva_isvara_bheda", tier: "para_tattva",
    en: "Jiva-Isvara-bheda", dev: "जीव-ईश्वर-भेद", kn: "ಜೀವ-ಈಶ್ವರ-ಭೇದ", hi: "जीव-ईश्वर-भेद",
    title: { en: "The eternal distinction of jiva and Isvara", dev: "जीव-ईश्वरयोः शाश्वत-भेदः", kn: "ಜೀವ-ಈಶ್ವರಗಳ ಶಾಶ್ವತ-ಭೇದ", hi: "जीव-ईश्वर का शाश्वत भेद" },
    note:  { en: "First of the five canonical bhedas (jiva-isvara, jiva-jiva, jada-isvara, jada-jiva, jada-jada). For Madhva, jivas are eternally distinct from Hari - never identical, never merging, even in mukti. The 'Paramatma' name itself implies a 'param' (other) atma.", dev: "पञ्च-भेदेषु प्रथमः (जीव-ईश्वर, जीव-जीव, जड-ईश्वर, जड-जीव, जड-जड)। मध्व-मते जीवाः हरेः नित्यं भिन्नाः - न ऐक्यम्, न लयः, मुक्तावपि। 'परमात्मन्' इति नाम-स्व-अर्थः एव 'परम्' (अन्यम्) आत्मानं सूचयति।", kn: "ಪಂಚ-ಭೇದಗಳಲ್ಲಿ ಮೊದಲನೆಯದು. ಮಧ್ವ-ಮತದಲ್ಲಿ ಜೀವಗಳು ಹರಿಯಿಂದ ನಿತ್ಯ ಭಿನ್ನ — ಐಕ್ಯವಿಲ್ಲ, ಲಯವಿಲ್ಲ, ಮುಕ್ತಿಯಲ್ಲಿಯೂ. 'ಪರಮಾತ್ಮಾ' ಎಂಬ ನಾಮವೇ 'ಪರಮ್' (ಅನ್ಯ) ಆತ್ಮವನ್ನು ಸೂಚಿಸುತ್ತದೆ.", hi: "पञ्च-भेदों में प्रथम। मध्व मत में जीव हरि से नित्य भिन्न हैं - न ऐक्य, न लय, मुक्ति में भी। 'परमात्मा' नाम स्वयं 'परम्' (अन्य) आत्मा को सूचित करता है।" },
    nama_ids: ["n_0012"],
  },
  {
    id: "c_kala_niyamakatva", tier: "para_tattva",
    en: "Kala-niyamakatva", dev: "काल-नियामकत्व", kn: "ಕಾಲ-ನಿಯಾಮಕತ್ವ", hi: "काल-नियामकत्व",
    title: { en: "Time-sovereignty", dev: "काल-नियामकत्वम्", kn: "ಕಾಲ-ನಿಯಾಮಕತ್ವ", hi: "काल-नियामकत्व" },
    note:  { en: "Hari is master of past, future, and present. The compound 'bhuta-bhavya-bhavat-prabhuh' compresses this into one name. The Gita 8.4 anchor: adhibhutam ksaro bhavah.", dev: "हरिः भूत-भविष्यत्-वर्तमानानां प्रभुः। 'भूत-भव्य-भवत्-प्रभुः' इति समासेन एक-नामतया प्रतिपादितम्। गीता ८।४ - 'अधिभूतं क्षरो भावः'।", kn: "ಹರಿ ಭೂತ-ಭವಿಷ್ಯತ್-ವರ್ತಮಾನಗಳ ಪ್ರಭು. 'ಭೂತ-ಭವ್ಯ-ಭವತ್-ಪ್ರಭುಃ' ಎಂಬ ಸಮಾಸದಿಂದ ಒಂದು ನಾಮವಾಗಿ ಪ್ರತಿಪಾದಿತ.", hi: "हरि भूत, भविष्य और वर्तमान के प्रभु हैं। 'भूत-भव्य-भवत्-प्रभुः' समास से एक नाम में पिरोया गया है।" },
    nama_ids: ["n_0004"],
  },
  {
    id: "c_yajna_svarupa", tier: "svarupa_guna",
    en: "Yajna-svarupa", dev: "यज्ञ-स्वरूप", kn: "ಯಜ್ಞ-ಸ್ವರೂಪ", hi: "यज्ञ-स्वरूप",
    title: { en: "Sacrifice-as-self", dev: "यज्ञ-स्वरूपम्", kn: "ಯಜ್ಞ-ಸ್ವರೂಪ", hi: "यज्ञ-स्वरूप" },
    note:  { en: "Hari is the Vedic-sacrificial act itself - its hetu, ashraya, and phala. The Vashatkara name asserts this at verse 1; Yajna at position 471 closes the loop. Cf. BG 4.24 brahmarpanam brahma havih.", dev: "हरिः वैदिक-यज्ञ-स्वरूपः - हेतुः, आश्रयः, फलं च। प्रथम-श्लोके वषट्कार-नाम्ना उद्घोषितम्; ४७१-स्थाने यज्ञ-नाम्ना समापितम्। गीता ४।२४ - 'ब्रह्मार्पणं ब्रह्म हविः'।", kn: "ಹರಿಯು ವೈದಿಕ-ಯಜ್ಞ-ಸ್ವರೂಪ - ಹೇತು, ಆಶ್ರಯ, ಫಲ. ಮೊದಲ ಶ್ಲೋಕದಲ್ಲಿ ವಷಟ್ಕಾರ ನಾಮದಿಂದ ಘೋಷಿತ; ೪೭೧ರಲ್ಲಿ ಯಜ್ಞ ನಾಮದಿಂದ ಸಮಾಪ್ತಿ.", hi: "हरि वैदिक यज्ञ-स्वरूप हैं - हेतु, आश्रय, फल। पहले श्लोक में 'वषट्कार' नाम से, और ४७१ में 'यज्ञ' नाम से।" },
    nama_ids: ["n_0003", "n_0471"],
  },
  {
    id: "c_sat_svarupa", tier: "svarupa_guna",
    en: "Sat-cit-ananda svarupa", dev: "सच्चिदानन्द-स्वरूप", kn: "ಸಚ್ಚಿದಾನಂದ-ಸ್ವರೂಪ", hi: "सच्चिदानन्द-स्वरूप",
    title: { en: "Existence-Consciousness-Bliss as essential nature", dev: "सच्चिदानन्द-स्वरूपम्", kn: "ಸಚ್ಚಿದಾನಂದ-ಸ್ವರೂಪ", hi: "सच्चिदानन्द-स्वरूप" },
    note:  { en: "Hari is the canonical Taittiriya 2.7 sat-cit-ananda Brahman. Putatma names the suddha-svabhava; Aksharah names sat; Anandah at position 557 names ananda; mantra at 300 names cit-svarupa.", dev: "हरिः तैत्तिरीयोपनिषद् २।७-स्थः सच्चिदानन्द-ब्रह्म-स्वरूपः। पूतात्म-नाम्ना शुद्ध-स्वभावम्; अक्षर-नाम्ना सत्; आनन्द-नाम्ना (५५७) आनन्दम्; मन्त्र-नाम्ना (३००) चित्।", kn: "ಹರಿ ತೈತ್ತಿರೀಯ ೨।೭ರ ಸಚ್ಚಿದಾನಂದ-ಬ್ರಹ್ಮ-ಸ್ವರೂಪ. ಪೂತಾತ್ಮ-ನಾಮದಿಂದ ಶುದ್ಧ-ಸ್ವಭಾವ; ಅಕ್ಷರ-ನಾಮದಿಂದ ಸತ್; ಆನಂದ-ನಾಮದಿಂದ (೫೫೭) ಆನಂದ.", hi: "हरि तैत्तिरीय २।७ के सच्चिदानन्द ब्रह्म-स्वरूप हैं। पूतात्मा से शुद्ध-स्वभाव; अक्षर से सत्; आनन्द (५५७) से आनन्द।" },
    nama_ids: ["n_0011", "n_0016", "n_0300", "n_0557", "n_0591", "n_0986"],
  },
  {
    id: "c_atma_svarupa", tier: "svarupa_guna",
    en: "Atma-svarupa", dev: "आत्म-स्वरूप", kn: "ಆತ್ಮ-ಸ್ವರೂಪ", hi: "आत्म-स्वरूप",
    title: { en: "Self-essence", dev: "आत्म-स्वरूपम्", kn: "ಆತ್ಮ-ಸ್ವರೂಪ", hi: "आत्म-स्वरूप" },
    note:  { en: "Hari as the inner essence of every being's atman. Distinct from antaryamitva (which is the dwelling-relation) - here it is the very being-of-essence.", dev: "हरिः प्रत्येक-भूतस्य आत्मनः अन्तःस्थ-स्वरूपम्। अन्तर्यामित्वात् (वासि-सम्बन्धात्) भिन्नम् - इदं सत्ता-स्वरूपम्।", kn: "ಹರಿ ಪ್ರತಿ ಭೂತದ ಆತ್ಮನ ಅಂತಃಸ್ಥ-ಸ್ವರೂಪ. ಅಂತರ್ಯಾಮಿತ್ವದಿಂದ (ವಾಸಿ-ಸಂಬಂಧದಿಂದ) ಭಿನ್ನ — ಇದು ಸತ್ತಾ-ಸ್ವರೂಪ.", hi: "हरि हर भूत के आत्मा का अन्तःस्थ स्वरूप। अन्तर्यामित्व (वासी-सम्बन्ध) से भिन्न - यह सत्ता-स्वरूप है।" },
    nama_ids: ["n_0007", "n_0986"],
  },
  {
    id: "c_srshti_kartrtva", tier: "lila_guna",
    en: "Srshti-kartrtva", dev: "सृष्टि-कर्तृत्व", kn: "ಸೃಷ್ಟಿ-ಕರ್ತೃತ್ವ", hi: "सृष्टि-कर्तृत्व",
    title: { en: "Creator-agency", dev: "सृष्टि-कर्तृत्वम्", kn: "ಸೃಷ್ಟಿ-ಕರ್ತೃತ್ವ", hi: "सृष्टि-कर्तृत्व" },
    note:  { en: "Hari's role as creator of all beings - the first of the srshti-sthiti-samhara trika. Bhutakrt (5), Bhutabhavana (8), Padmanabha (48) are the proper names; the cosmogonic image is the lotus-from-navel.", dev: "सृष्टि-स्थिति-संहार-त्रिकस्य प्रथमम्। भूतकृत् (५), भूतभावन (८), पद्मनाभ (४८) इति नाम-स्वरूपाणि; नाभि-कमल-उद्भव-ब्रह्मा इति प्रतीकम्।", kn: "ಸೃಷ್ಟಿ-ಸ್ಥಿತಿ-ಸಂಹಾರ-ತ್ರಿಕದ ಮೊದಲನೇ. ಭೂತಕೃತ್ (೫), ಭೂತಭಾವನ (೮), ಪದ್ಮನಾಭ (೪೮) ನಾಮಗಳು; ನಾಭಿ-ಕಮಲದಿಂದ ಬ್ರಹ್ಮನ ಉದ್ಭವ ಪ್ರತೀಕ.", hi: "सृष्टि-स्थिति-संहार-त्रिक का प्रथम। भूतकृत् (५), भूतभावन (८), पद्मनाभ (४८) नामस्वरूप; नाभि-कमल से ब्रह्मा का उद्भव प्रतीक।" },
    nama_ids: ["n_0005", "n_0008", "n_0048"],
  },
  {
    id: "c_sthiti_kartrtva", tier: "lila_guna",
    en: "Sthiti-kartrtva", dev: "स्थिति-कर्तृत्व", kn: "ಸ್ಥಿತಿ-ಕರ್ತೃತ್ವ", hi: "स्थिति-कर्तृत्व",
    title: { en: "Sustainer-agency", dev: "स्थिति-कर्तृत्वम्", kn: "ಸ್ಥಿತಿ-ಕರ್ತೃತ್ವ", hi: "स्थिति-कर्तृत्व" },
    note:  { en: "Hari's role as sustainer - the bhrt-root (bear/maintain) names. Bhutabhrt (6) is the proper name in the opening verse.", dev: "सृष्टि-स्थिति-संहार-त्रिकस्य द्वितीयम्। भूतभृत् (६) इति प्रथम-श्लोक-स्थं नाम।", kn: "ಸೃಷ್ಟಿ-ಸ್ಥಿತಿ-ಸಂಹಾರ-ತ್ರಿಕದ ಎರಡನೆಯದು. ಭೂತಭೃತ್ (೬) ಪ್ರಥಮ-ಶ್ಲೋಕದ ನಾಮ.", hi: "सृष्टि-स्थिति-संहार-त्रिक का द्वितीय। भूतभृत् (६) प्रथम श्लोक में।" },
    nama_ids: ["n_0006"],
  },
  {
    id: "c_avatara_rupa", tier: "lila_guna",
    en: "Avatara-rupa", dev: "अवतार-रूप", kn: "ಅವತಾರ-ರೂಪ", hi: "अवतार-रूप",
    title: { en: "Forms-of-descent", dev: "अवतार-रूपाणि", kn: "ಅವತಾರ-ರೂಪಗಳು", hi: "अवतार-रूप" },
    note:  { en: "The dasa-avatara plus Krishna and Narasimha as the proper-name forms in this corpus. Madhva: avataras are not karma-baddha bodies but iccha-prakata svarupa-aikya manifestations of Hari himself.", dev: "दशावताराः कृष्ण-नारसिंहाभ्यां सह। मध्व-मते अवताराः न कर्म-बद्धाः शरीराः; इच्छा-प्रकटाः स्वरूप-ऐक्येन हरेरेव।", kn: "ದಶಾವತಾರಗಳು ಜೊತೆಗೆ ಕೃಷ್ಣ-ನಾರಸಿಂಹಗಳು. ಮಧ್ವ-ಮತದಲ್ಲಿ ಅವತಾರಗಳು ಕರ್ಮ-ಬದ್ಧ ಶರೀರಗಳಲ್ಲ; ಇಚ್ಛಾ-ಪ್ರಕಟ ಸ್ವರೂಪ-ಐಕ್ಯದಿಂದ ಹರಿಯ.", hi: "दशावतार सहित कृष्ण-नारसिंह। मध्व मत में अवतार कर्म-बद्ध शरीर नहीं; इच्छा-प्रकट स्वरूप-ऐक्य से हरि के स्वयं।" },
    nama_ids: ["n_0057", "n_0073", "n_0126", "n_0215", "n_0220", "n_0260", "n_0337", "n_0490", "n_0530", "n_0594", "n_0963"],
  },
  {
    id: "c_karunya", tier: "karunya_guna",
    en: "Karunya", dev: "कारुण्य", kn: "ಕಾರುಣ್ಯ", hi: "कारुण्य",
    title: { en: "Compassion/mercy", dev: "कारुण्यम्", kn: "ಕಾರುಣ್ಯ", hi: "कारुण्य" },
    note:  { en: "The mercy-attribute. Hari-nama itself encodes papa-harana; vatsalya in shloka 78. Karunya is the bridge from sva-rupa-guna into bhakta-sambandha.", dev: "कारुण्य-गुणः। हरि-नामैव पाप-हरण-वाची; भक्त-वत्सलता ७८-श्लोके। स्वरूप-गुणतः भक्त-सम्बन्ध-गुण-पर्यन्तं सेतुः।", kn: "ಕಾರುಣ್ಯ-ಗುಣ. ಹರಿ-ನಾಮವೇ ಪಾಪ-ಹರಣ-ವಾಚಿ; ಭಕ್ತ-ವತ್ಸಲತೆ ೭೮-ಶ್ಲೋಕದಲ್ಲಿ. ಸ್ವರೂಪ-ಗುಣದಿಂದ ಭಕ್ತ-ಸಂಬಂಧ-ಗುಣದವರೆಗೆ ಸೇತು.", hi: "कारुण्य-गुण। हरि-नाम स्वयं पाप-हरण-वाची; भक्त-वत्सलता ७८-श्लोक में।" },
    nama_ids: ["n_0008", "n_0074", "n_0126", "n_0641", "n_0656", "n_0073"],
  },
  {
    id: "c_bhakta_vatsala", tier: "bhakta_sambandha",
    en: "Bhakta-vatsala", dev: "भक्त-वत्सल", kn: "ಭಕ್ತ-ವತ್ಸಲ", hi: "भक्त-वत्सल",
    title: { en: "Devotee-affection", dev: "भक्त-वत्सलत्वम्", kn: "ಭಕ್ತ-ವತ್ಸಲತ್ವ", hi: "भक्त-वत्सलत्व" },
    note:  { en: "Specific tenderness toward devotees - vatsalya is mother-cow-for-calf love. For Madhva, this is svabhava-sidha (essential), not contingent.", dev: "भक्तेषु विशिष्ट-स्नेहः - मातु-धेनु-वत्स-वत् वत्सलता। मध्व-मते इदं स्वभाव-सिद्धम्, न प्रासङ्गिकम्।", kn: "ಭಕ್ತರಲ್ಲಿ ವಿಶಿಷ್ಟ-ಸ್ನೇಹ — ಮಾತೃ-ಧೇನು-ವತ್ಸದಂತೆ ವತ್ಸಲತೆ. ಮಧ್ವ-ಮತದಲ್ಲಿ ಇದು ಸ್ವಭಾವ-ಸಿದ್ಧ, ಪ್ರಾಸಂಗಿಕವಲ್ಲ.", hi: "भक्तों में विशिष्ट स्नेह - मातृ-धेनु-वत्स के समान वत्सलता। मध्व मत में यह स्वभाव-सिद्ध है, प्रासङ्गिक नहीं।" },
    nama_ids: ["n_0057", "n_0197", "n_0215", "n_0490", "n_0594", "n_0777", "n_0780"],
  },
  {
    id: "c_lakshmi_sambandha", tier: "para_tattva",
    en: "Lakshmi-sambandha", dev: "लक्ष्मी-सम्बन्ध", kn: "ಲಕ್ಷ್ಮೀ-ಸಂಬಂಧ", hi: "लक्ष्मी-सम्बन्ध",
    title: { en: "The Lakshmi-relation", dev: "लक्ष्मी-सम्बन्धः", kn: "ಲಕ್ಷ್ಮೀ-ಸಂಬಂಧ", hi: "लक्ष्मी-सम्बन्ध" },
    note:  { en: "The eternal Sri-Vishnu mithuna. For Madhva, Lakshmi is the highest jiva - the kuta-stha akshara of BG 15.16 - eternally subordinate to Hari but supreme above all other jivas.", dev: "नित्य-श्री-विष्णु-मिथुन-तत्त्वम्। मध्व-मते लक्ष्मीः उच्चतमं जीव-तत्त्वम्, गीता १५।१६-स्थः कूटस्थ अक्षरः, हरेः नित्य-परतन्त्रा अथ च सर्व-इतर-जीवेभ्यः उत्तमा।", kn: "ನಿತ್ಯ-ಶ್ರೀ-ವಿಷ್ಣು-ಮಿಥುನ-ತತ್ತ್ವ. ಮಧ್ವ-ಮತದಲ್ಲಿ ಲಕ್ಷ್ಮೀ ಉಚ್ಚತಮ ಜೀವ-ತತ್ತ್ವ, ಗೀತಾ ೧೫।೧೬ರ ಕೂಟಸ್ಥ ಅಕ್ಷರ, ಹರಿಯ ನಿತ್ಯ-ಪರತಂತ್ರಾ ಆದರೆ ಉಳಿದೆಲ್ಲ ಜೀವಗಳಿಗಿಂತ ಉತ್ತಮ.", hi: "नित्य श्री-विष्णु मिथुन-तत्त्व। मध्व मत में लक्ष्मी उच्चतम जीव-तत्त्व, गीता १५।१६ का कूटस्थ अक्षर, हरि के नित्य-परतन्त्र पर बाकी सब जीवों से उत्तम।" },
    nama_ids: ["n_0643"],
  },
  {
    id: "c_moksha_prada", tier: "mokshaprada",
    en: "Moksha-prada", dev: "मोक्ष-प्रद", kn: "ಮೋಕ್ಷ-ಪ್ರದ", hi: "मोक्ष-प्रद",
    title: { en: "Liberation-bestowing", dev: "मोक्ष-प्रदत्वम्", kn: "ಮೋಕ್ಷ-ಪ್ರದತ್ವ", hi: "मोक्ष-प्रदत्व" },
    note:  { en: "Hari is the sole-cause of mukti. Mukunda (515), Muktanam-parama-gatih (13), and Hari himself (656) are the proper-name forms. For Madhva, mukti has tāratamya - sālokya, sāmīpya, sārūpya, sāyujya - all granted by Hari.", dev: "हरिः मुक्तेः एक-कारणम्। मुकुन्द (५१५), मुक्तानां परमा गतिः (१३), हरिः (६५६) - नाम-स्वरूपाणि। मध्व-मते मुक्तौ तारतम्यम् - सालोक्य-सामीप्य-सारूप्य-सायुज्य - सर्वाः हरि-प्रसादात्।", kn: "ಹರಿ ಮುಕ್ತಿಯ ಏಕ-ಕಾರಣ. ಮುಕುಂದ (೫೧೫), ಮುಕ್ತಾನಾಂ ಪರಮಾ ಗತಿಃ (೧೩), ಹರಿ (೬೫೬) ನಾಮ-ಸ್ವರೂಪಗಳು. ಮಧ್ವ-ಮತದಲ್ಲಿ ಮುಕ್ತಿಯಲ್ಲಿ ತಾರತಮ್ಯ — ಎಲ್ಲ ಹರಿ-ಪ್ರಸಾದದಿಂದ.", hi: "हरि मुक्ति के एकमात्र कारण। मुकुन्द (५१५), मुक्तानां परमा गतिः (१३), हरि (६५६) नाम-स्वरूप। मध्व मत में मुक्ति में तारतम्य।" },
    nama_ids: ["n_0013", "n_0515", "n_0656", "n_0886", "n_0986"],
  },
  {
    id: "c_nihsima_paripurnatva", tier: "para_tattva",
    en: "Niḥsīma-paripūrṇatva", dev: "निःसीम-परिपूर्णत्व", kn: "ನಿಃಸೀಮ-ಪರಿಪೂರ್ಣತ್ವ", hi: "निःसीम-परिपूर्णता",
    title: { en: "Boundless completeness", dev: "निःसीम-परिपूर्णत्वम्", kn: "ನಿಃಸೀಮ-ಪರಿಪೂರ್ಣತೆ", hi: "निःसीम-परिपूर्णता" },
    note:  { en: "Hari is infinite and complete; no want, no limit. Distinct from limited devatās. Avyayaḥ and Aksaraḥ name this.", dev: "हरिः अनन्तः परिपूर्णश्च; न तस्य न्यूनता न सीमा। 'अव्ययः' 'अक्षरः' इति नाम-द्वयं अस्य निर्देशकम्।", kn: "ಹರಿಯು ಅನಂತ ಪರಿಪೂರ್ಣ; ಊನತೆಯಿಲ್ಲ, ಸೀಮೆಯಿಲ್ಲ. ಅವ್ಯಯ ಅಕ್ಷರ ಎಂಬ ನಾಮಗಳಿಂದ ಸೂಚಿತ.", hi: "हरि अनन्त और परिपूर्ण हैं; न उनमें कोई कमी है, न कोई सीमा। 'अव्यय' और 'अक्षर' नाम इसी को व्यक्त करते हैं।" },
    nama_ids: ["n_0011", "n_0013", "n_0014", "n_0017", "n_0036"],
  },
  {
    id: "c_pancha_bheda_mula", tier: "para_tattva",
    en: "Pañca-bheda-mūla", dev: "पञ्च-भेद-मूल", kn: "ಪಂಚ-ಭೇದ-ಮೂಲ", hi: "पञ्च-भेद-मूल",
    title: { en: "Foundation of the five canonical distinctions", dev: "पञ्च-भेदस्य मूलम्", kn: "ಪಂಚ-ಭೇದದ ಮೂಲ", hi: "पञ्च-भेद का मूल" },
    note:  { en: "The five eternal bhedas (jīva-īśvara, jīva-jīva, jaḍa-īśvara, jaḍa-jīva, jaḍa-jaḍa) are grounded in Hari's separateness.", dev: "पञ्च-नित्य-भेदाः (जीव-ईश्वर, जीव-जीव, जड-ईश्वर, जड-जीव, जड-जड) हरेः अन्यत्वे प्रतिष्ठिताः।", kn: "ಪಂಚ-ನಿತ್ಯ-ಭೇದಗಳು ಹರಿಯ ಅನ್ಯತ್ವದಲ್ಲಿ ಪ್ರತಿಷ್ಠಿತ.", hi: "पाँच नित्य भेद हरि के अन्यत्व पर आधारित हैं — मध्व का मूल सिद्धान्त।" },
    nama_ids: ["n_0012", "n_0017"],
  },
  {
    id: "c_avyaya_svarupa", tier: "para_tattva",
    en: "Avyaya-svarūpa", dev: "अव्यय-स्वरूप", kn: "ಅವ್ಯಯ-ಸ್ವರೂಪ", hi: "अव्यय-स्वरूप",
    title: { en: "Imperishable essence", dev: "अव्यय-स्वरूपम्", kn: "ಅವ್ಯಯ-ಸ್ವರೂಪ", hi: "अव्यय-स्वरूप" },
    note:  { en: "Hari undergoes no decay or transformation. The name 'avyayaḥ' at position 13 directly states it.", dev: "हरिः निर्विकारः अप्रच्युतः। १३-स्थम् 'अव्ययः' इति नाम साक्षात् एतत् घोषयति।", kn: "ಹರಿಯು ನಿರ್ವಿಕಾರ ಅಪ್ರಚ್ಯುತ. 'ಅವ್ಯಯ' ನಾಮ ಸಾಕ್ಷಾತ್ ಇದನ್ನು ಘೋಷಿಸುತ್ತದೆ.", hi: "हरि निर्विकार और अच्युत हैं। 'अव्यय' नाम (पद १३) सीधे यही कहता है।" },
    nama_ids: ["n_0013", "n_0049", "n_0322", "n_0884"],
  },
  {
    id: "c_trikala_jna", tier: "para_tattva",
    en: "Trikāla-jña", dev: "त्रिकाल-ज्ञ", kn: "ತ್ರಿಕಾಲ-ಜ್ಞ", hi: "त्रिकाल-ज्ञ",
    title: { en: "Knower of past, present, and future", dev: "त्रिकाल-ज्ञत्वम्", kn: "ತ್ರಿಕಾಲ-ಜ್ಞತ್ವ", hi: "त्रिकाल-ज्ञता" },
    note:  { en: "Hari knows all three times. The compound bhūtabhavyabhavatprabhuḥ at position 4 names this.", dev: "हरिः त्रिकाल-ज्ञः। 'भूतभव्यभवत्प्रभुः' इति ४-स्थं नाम एतत् प्रतिपादयति।", kn: "ಹರಿಯು ತ್ರಿಕಾಲ-ಜ್ಞ. 'ಭೂತಭವ್ಯಭವತ್ಪ್ರಭುಃ' ೪-ಸ್ಥಾನದ ನಾಮ.", hi: "हरि तीनों कालों के ज्ञाता हैं — 'भूतभव्यभवत्प्रभुः' (पद ४) यही कहता है।" },
    nama_ids: ["n_0004"],
  },
  {
    id: "c_cit_svarupa", tier: "svarupa_guna",
    en: "Cit-svarūpa", dev: "चित्-स्वरूप", kn: "ಚಿತ್-ಸ್ವರೂಪ", hi: "चित्-स्वरूप",
    title: { en: "Consciousness as essence", dev: "चित्-स्वरूपम्", kn: "ಚಿತ್-ಸ್ವರೂಪ", hi: "चित्-स्वरूप" },
    note:  { en: "Pure consciousness — Hari knows all without instruments.", dev: "शुद्ध-चैतन्य-स्वरूपम्। हरिः अन्तःकरण-निरपेक्षेण सर्वं जानाति।", kn: "ಶುದ್ಧ-ಚೈತನ್ಯ-ಸ್ವರೂಪ. ಹರಿ ಅಂತಃಕರಣ-ನಿರಪೇಕ್ಷವಾಗಿ ಎಲ್ಲ ತಿಳಿಯುತ್ತಾನೆ.", hi: "शुद्ध चैतन्य-स्वरूप। हरि बिना किसी साधन के सब कुछ जानते हैं।" },
    nama_ids: ["n_0300", "n_0421", "n_0691"],
  },
  {
    id: "c_ananda_svarupa", tier: "svarupa_guna",
    en: "Ānanda-svarūpa", dev: "आनन्द-स्वरूप", kn: "ಆನಂದ-ಸ್ವರೂಪ", hi: "आनन्द-स्वरूप",
    title: { en: "Bliss as essence", dev: "आनन्द-स्वरूपम्", kn: "ಆನಂದ-ಸ್ವರೂಪ", hi: "आनन्द-स्वरूप" },
    note:  { en: "Hari is the source and substance of all joy. Ānandaḥ at 557 names this.", dev: "हरिः सर्व-आनन्द-स्रोतः, स्वरूप-भूतः। ५५७-स्थम् 'आनन्दः' इति नाम।", kn: "ಹರಿ ಸಮಸ್ತ ಆನಂದದ ಉಗಮ ಮತ್ತು ಸ್ವರೂಪ. ೫೫೭-ಸ್ಥಾನದ 'ಆನಂದ' ನಾಮ.", hi: "हरि समस्त आनन्द के स्रोत और स्वरूप हैं। 'आनन्द' नाम (पद ५५७)।" },
    nama_ids: ["n_0557", "n_0600"],
  },
  {
    id: "c_jnana_guna", tier: "svarupa_guna",
    en: "Jñāna-guṇa", dev: "ज्ञान-गुण", kn: "ಜ್ಞಾನ-ಗುಣ", hi: "ज्ञान-गुण",
    title: { en: "Omniscience attribute", dev: "ज्ञान-गुणः", kn: "ಜ್ಞಾನ-ಗುಣ", hi: "ज्ञान-गुण" },
    note:  { en: "Hari is sarvajña — all-knowing of past, present, future and all hidden things.", dev: "हरिः सर्वज्ञः - अतीतानागत-वर्तमान-गुप्त-सर्व-वस्तु-वेत्ता।", kn: "ಹರಿ ಸರ್ವಜ್ಞ - ಎಲ್ಲ ಕಾಲ ಮತ್ತು ಗುಪ್ತ ವಸ್ತುಗಳ ಜ್ಞಾತಾ.", hi: "हरि सर्वज्ञ हैं — भूत, भविष्य, वर्तमान और गुप्त सब वस्तुओं को जानने वाले।" },
    nama_ids: ["n_0021", "n_0454", "n_0686"],
  },
  {
    id: "c_bala_guna", tier: "svarupa_guna",
    en: "Bala-guṇa", dev: "बल-गुण", kn: "ಬಲ-ಗುಣ", hi: "बल-गुण",
    title: { en: "Infinite strength", dev: "बल-गुणः", kn: "ಬಲ-ಗುಣ", hi: "बल-गुण" },
    note:  { en: "Hari's bala is unsurpassable. Names like Mahābala, Mahāvīrya predicate this.", dev: "हरेः बलं निरतिशयम्। 'महाबलः', 'महावीर्यः' इति नामानि।", kn: "ಹರಿಯ ಬಲ ನಿರತಿಶಯ. 'ಮಹಾಬಲ', 'ಮಹಾವೀರ್ಯ' ಎಂಬ ನಾಮಗಳಿಂದ ಸೂಚಿತ.", hi: "हरि का बल निरतिशय है। 'महाबल', 'महावीर्य' नाम यही कहते हैं।" },
    nama_ids: ["n_0172", "n_0174", "n_0182"],
  },
  {
    id: "c_aishvarya_guna", tier: "svarupa_guna",
    en: "Aiśvarya-guṇa", dev: "ऐश्वर्य-गुण", kn: "ಐಶ್ವರ್ಯ-ಗುಣ", hi: "ऐश्वर्य-गुण",
    title: { en: "Lordliness attribute", dev: "ऐश्वर्य-गुणः", kn: "ಐಶ್ವರ್ಯ-ಗುಣ", hi: "ऐश्वर्य-गुण" },
    note:  { en: "Hari is Īśvara of all — none above, none equal. Names like Īśvaraḥ, Sarveśvaraḥ.", dev: "हरिः सर्वेषाम् ईश्वरः - न तस्य अधिकः न समः। 'ईश्वरः' 'सर्वेश्वरः' इति नामानि।", kn: "ಹರಿ ಎಲ್ಲರ ಈಶ್ವರ - ಅಧಿಕನಿಲ್ಲ ಸಮನಿಲ್ಲ. 'ಈಶ್ವರ' 'ಸರ್ವೇಶ್ವರ' ನಾಮಗಳು.", hi: "हरि सब के ईश्वर हैं — कोई अधिक नहीं, कोई सम नहीं। 'ईश्वर', 'सर्वेश्वर' नाम।" },
    nama_ids: ["n_0036", "n_0074", "n_0096", "n_0357"],
  },
  {
    id: "c_virya_tejas", tier: "svarupa_guna",
    en: "Vīrya-tejas", dev: "वीर्य-तेजस्", kn: "ವೀರ್ಯ-ತೇಜಸ್", hi: "वीर्य-तेजस्",
    title: { en: "Heroic vigor and radiance", dev: "वीर्य-तेजसी", kn: "ವೀರ್ಯ-ತೇಜಸ್", hi: "वीर्य-तेजस्" },
    note:  { en: "Hari blazes with vīrya and tejas; the radiance of his form scatters all darkness.", dev: "हरिः वीर्येण तेजसा च देदीप्यमानः।", kn: "ಹರಿ ವೀರ್ಯ-ತೇಜಸ್ಸುಗಳಿಂದ ಪ್ರಜ್ವಲಿಸುತ್ತಾನೆ.", hi: "हरि वीर्य और तेज से प्रज्वलित हैं।" },
    nama_ids: ["n_0174", "n_0252"],
  },
  {
    id: "c_samhara_kartrtva", tier: "lila_guna",
    en: "Saṃhāra-kartṛtva", dev: "संहार-कर्तृत्व", kn: "ಸಂಹಾರ-ಕರ್ತೃತ್ವ", hi: "संहार-कर्तृत्व",
    title: { en: "Dissolver agency", dev: "संहार-कर्तृत्वम्", kn: "ಸಂಹಾರ-ಕರ್ತೃತ್ವ", hi: "संहार-कर्तृत्व" },
    note:  { en: "Hari is the final dissolver. Names like Rudraḥ, Antakaḥ, Saṃhartṛ predicate this.", dev: "हरिः सर्व-संहार-कर्ता।", kn: "ಹರಿ ಸರ್ವ-ಸಂಹಾರ-ಕರ್ತ.", hi: "हरि सर्व-संहार-कर्ता हैं।" },
    nama_ids: ["n_0148", "n_0159", "n_0354", "n_0437", "n_0511", "n_0720", "n_0837", "n_0932"],
  },
  {
    id: "c_avatara_matsya", tier: "lila_guna",
    en: "Matsyāvatāra", dev: "मत्स्यावतार", kn: "ಮತ್ಸ್ಯಾವತಾರ", hi: "मत्स्यावतार",
    title: { en: "Matsya — the fish incarnation", dev: "मत्स्यावतारः", kn: "ಮತ್ಸ್ಯಾವತಾರ", hi: "मत्स्यावतार" },
    note:  { en: "First daśāvatāra. Hari as fish who rescues Vedas and Manu from the cosmic flood.", dev: "दशावतारस्य प्रथमः।", kn: "ದಶಾವತಾರದ ಪ್ರಥಮ.", hi: "दशावतारों में प्रथम। हरि मत्स्य-रूप से वेद और मनु को प्रलय से बचाते हैं।" },
    nama_ids: [],
  },
  {
    id: "c_avatara_kurma", tier: "lila_guna",
    en: "Kūrmāvatāra", dev: "कूर्मावतार", kn: "ಕೂರ್ಮಾವತಾರ", hi: "कूर्मावतार",
    title: { en: "Kūrma — the tortoise incarnation", dev: "कूर्मावतारः", kn: "ಕೂರ್ಮಾವತಾರ", hi: "कूर्मावतार" },
    note:  { en: "Hari as tortoise supports Mandara mountain during the samudra-manthana.", dev: "हरिः कूर्म-रूपेण समुद्र-मन्थने मन्दर-पर्वतं धरति।", kn: "ಹರಿ ಕೂರ್ಮ-ರೂಪದಿಂದ ಸಮುದ್ರ-ಮಂಥನದಲ್ಲಿ ಮಂದರ-ಪರ್ವತವನ್ನು ಧರಿಸುತ್ತಾನೆ.", hi: "हरि कूर्म-रूप से समुद्र-मन्थन में मन्दर पर्वत को धारण करते हैं।" },
    nama_ids: [],
  },
  {
    id: "c_avatara_varaha", tier: "lila_guna",
    en: "Varāhāvatāra", dev: "वराहावतार", kn: "ವರಾಹಾವತಾರ", hi: "वराहावतार",
    title: { en: "Varāha — the boar incarnation", dev: "वराहावतारः", kn: "ವರಾಹಾವತಾರ", hi: "वराहावतार" },
    note:  { en: "Hari as boar lifts the earth from the cosmic ocean.", dev: "हरिः वराह-रूपेण भूमिं रसातलात् उद्धरति।", kn: "ಹರಿ ವರಾಹ-ರೂಪದಿಂದ ಭೂಮಿಯನ್ನು ರಸಾತಲದಿಂದ ಎತ್ತುತ್ತಾನೆ.", hi: "हरि वराह-रूप से भूमि को रसातल से उठाते हैं।" },
    nama_ids: ["n_0565"],
  },
  {
    id: "c_avatara_narasimha", tier: "lila_guna",
    en: "Narasiṃhāvatāra", dev: "नरसिंहावतार", kn: "ನರಸಿಂಹಾವತಾರ", hi: "नरसिंहावतार",
    title: { en: "Narasiṃha — the man-lion incarnation", dev: "नरसिंहावतारः", kn: "ನರಸಿಂಹಾವತಾರ", hi: "नरसिंहावतार" },
    note:  { en: "Hari as man-lion slays Hiraṇyakaśipu and saves Prahlāda.", dev: "हरिः नरसिंह-रूपेण हिरण्यकशिपुं हन्ति, प्रह्लादं रक्षति।", kn: "ಹರಿ ನರಸಿಂಹ-ರೂಪದಿಂದ ಹಿರಣ್ಯಕಶಿಪುವನ್ನು ಸಂಹರಿಸಿ ಪ್ರಹ್ಲಾದನನ್ನು ರಕ್ಷಿಸುತ್ತಾನೆ.", hi: "हरि नरसिंह-रूप से हिरण्यकशिपु का संहार करके प्रह्लाद की रक्षा करते हैं।" },
    nama_ids: ["n_0021"],
  },
  {
    id: "c_avatara_vamana", tier: "lila_guna",
    en: "Vāmanāvatāra", dev: "वामनावतार", kn: "ವಾಮನಾವತಾರ", hi: "वामनावतार",
    title: { en: "Vāmana — the dwarf-Trivikrama incarnation", dev: "वामनावतारः", kn: "ವಾಮನಾವತಾರ", hi: "वामनावतार" },
    note:  { en: "Hari as Vāmana spans the three worlds in three strides.", dev: "हरिः वामन-रूपेण त्रिभिः पादैः त्रैलोक्यं क्रामति।", kn: "ಹರಿ ವಾಮನ-ರೂಪದಿಂದ ಮೂರು ಹೆಜ್ಜೆಗಳಿಂದ ತ್ರೈಲೋಕ್ಯ ಕ್ರಮಿಸುತ್ತಾನೆ.", hi: "हरि वामन-रूप से तीन पगों में त्रैलोक्य को नाप लेते हैं।" },
    nama_ids: ["n_0151", "n_0152", "n_0532"],
  },
  {
    id: "c_avatara_parashurama", tier: "lila_guna",
    en: "Paraśurāmāvatāra", dev: "परशुरामावतार", kn: "ಪರಶುರಾಮಾವತಾರ", hi: "परशुरामावतार",
    title: { en: "Paraśurāma — the axe-wielding incarnation", dev: "परशुरामावतारः", kn: "ಪರಶುರಾಮಾವತಾರ", hi: "परशुरामावतार" },
    note:  { en: "Hari as Paraśurāma destroys the rebellious kṣatriya tyranny twenty-one times.", dev: "हरिः परशुराम-रूपेण क्षत्र-कुलं एकविंशति-वारं संहरति।", kn: "ಹರಿ ಪರಶುರಾಮ-ರೂಪದಿಂದ ಕ್ಷತ್ರಿಯ ಕುಲವನ್ನು ೨೧ ಬಾರಿ ಸಂಹರಿಸುತ್ತಾನೆ.", hi: "हरि परशुराम-रूप से क्षत्रिय कुल का इक्कीस बार संहार करते हैं।" },
    nama_ids: ["n_0571"],
  },
  {
    id: "c_avatara_rama", tier: "lila_guna",
    en: "Rāmāvatāra", dev: "रामावतार", kn: "ರಾಮಾವತಾರ", hi: "रामावतार",
    title: { en: "Rāma — the king-incarnation", dev: "रामावतारः", kn: "ರಾಮಾವತಾರ", hi: "रामावतार" },
    note:  { en: "Hari as Rāma incarnates as the ideal king to slay Rāvaṇa.", dev: "हरिः राम-रूपेण रावण-वधार्थम् आदर्श-राज-रूपेण अवतीर्णः।", kn: "ಹರಿ ರಾಮ-ರೂಪದಿಂದ ರಾವಣ-ವಧಕ್ಕಾಗಿ ಆದರ್ಶ-ರಾಜ-ರೂಪವಾಗಿ ಅವತರಿಸುತ್ತಾನೆ.", hi: "हरि राम-रूप से रावण-वध के लिए आदर्श राजा के रूप में अवतरित होते हैं।" },
    nama_ids: ["n_0394", "n_0488", "n_0545"],
  },
  {
    id: "c_avatara_krishna", tier: "lila_guna",
    en: "Kṛṣṇāvatāra", dev: "कृष्णावतार", kn: "ಕೃಷ್ಣಾವತಾರ", hi: "कृष्णावतार",
    title: { en: "Kṛṣṇa — the divine cowherd incarnation", dev: "कृष्णावतारः", kn: "ಕೃಷ್ಣಾವತಾರ", hi: "कृष्णावतार" },
    note:  { en: "Hari as Kṛṣṇa, Govinda, Vāsudeva — the avatāra of the Bhāgavata-purāṇa and Bhagavad-gītā.", dev: "हरिः कृष्ण-रूपेण - गोविन्दः, वासुदेवः, गीताकारः।", kn: "ಹರಿ ಕೃಷ್ಣ-ರೂಪದಿಂದ - ಗೋವಿಂದ, ವಾಸುದೇವ, ಗೀತಾಕಾರ.", hi: "हरि कृष्ण-रूप से — गोविन्द, वासुदेव, गीताकार, भागवत-नायक।" },
    nama_ids: ["n_0057", "n_0187", "n_0555", "n_0701"],
  },
  {
    id: "c_avatara_buddha", tier: "lila_guna",
    en: "Buddhāvatāra", dev: "बुद्धावतार", kn: "ಬುದ್ಧಾವತಾರ", hi: "बुद्धावतार",
    title: { en: "Buddha — the mohana-avatāra", dev: "बुद्धावतारः", kn: "ಬುದ್ಧಾವತಾರ", hi: "बुद्धावतार" },
    note:  { en: "Hari as Buddha confounds the asuras to maintain dharmic balance.", dev: "हरिः बुद्ध-रूपेण असुरान् मोहयित्वा धर्म-व्यवस्थां रक्षति।", kn: "ಹರಿ ಬುದ್ಧ-ರೂಪದಿಂದ ಅಸುರರನ್ನು ಮೋಹಗೊಳಿಸಿ ಧರ್ಮ-ವ್ಯವಸ್ಥೆಯನ್ನು ರಕ್ಷಿಸುತ್ತಾನೆ.", hi: "हरि बुद्ध-रूप से असुरों को मोहित कर धर्म-व्यवस्था की रक्षा करते हैं।" },
    nama_ids: [],
  },
  {
    id: "c_avatara_kalki", tier: "lila_guna",
    en: "Kalkyavatāra", dev: "कल्क्यवतार", kn: "ಕಲ್ಕ್ಯವತಾರ", hi: "कल्क्यवतार",
    title: { en: "Kalki — the future incarnation", dev: "कल्क्यवतारः", kn: "ಕಲ್ಕ್ಯವತಾರ", hi: "कल्क्यवतार" },
    note:  { en: "Hari as Kalki will close the Kali age and re-establish dharma at the cycle's end.", dev: "हरिः कल्कि-रूपेण कलि-युगस्य अन्ते धर्मं प्रतिष्ठापयिष्यति।", kn: "ಹರಿ ಕಲ್ಕಿ-ರೂಪದಿಂದ ಕಲಿ-ಯುಗದ ಅಂತ್ಯದಲ್ಲಿ ಧರ್ಮವನ್ನು ಮರುಸ್ಥಾಪಿಸುತ್ತಾನೆ.", hi: "हरि कल्कि-रूप से कलि-युग के अन्त में धर्म की पुनःस्थापना करेंगे।" },
    nama_ids: [],
  },
  {
    id: "c_avatara_hayagriva", tier: "lila_guna",
    en: "Hayagrīvāvatāra", dev: "हयग्रीवावतार", kn: "ಹಯಗ್ರೀವಾವತಾರ", hi: "हयग्रीवावतार",
    title: { en: "Hayagrīva — the horse-headed avatāra of knowledge", dev: "हयग्रीवावतारः", kn: "ಹಯಗ್ರೀವಾವತಾರ", hi: "हयग्रीवावतार" },
    note:  { en: "Hari as Hayagrīva, horse-headed avatāra who recovers the Vedas.", dev: "हरिः हयग्रीव-रूपेण मधु-कैटभाभ्यां वेदान् रक्षति।", kn: "ಹರಿ ಹಯಗ್ರೀವ-ರೂಪದಿಂದ ಮಧು-ಕೈಟಭರಿಂದ ವೇದಗಳನ್ನು ಮರಳಿಸುತ್ತಾನೆ.", hi: "हरि हयग्रीव-रूप से मधु-कैटभ से वेदों को पुनः प्राप्त करते हैं।" },
    nama_ids: [],
  },
  {
    id: "c_bhakta_vatsalatva", tier: "karunya_guna",
    en: "Vātsalyatva", dev: "वात्सल्यत्व", kn: "ವಾತ್ಸಲ್ಯತ್ವ", hi: "वात्सल्यता",
    title: { en: "Maternal affection for devotees", dev: "वात्सल्यत्वम्", kn: "ವಾತ್ಸಲ್ಯತ್ವ", hi: "वात्सल्यता" },
    note:  { en: "Hari's affection toward devotees exceeds that of a mother for child.", dev: "हरेः भक्तेषु वात्सल्यं मातुः अपेक्षया अधिकम्।", kn: "ಹರಿಗೆ ಭಕ್ತರ ಮೇಲೆ ತಾಯಿಗಿಂತ ಹೆಚ್ಚು ವಾತ್ಸಲ್ಯ.", hi: "हरि का भक्तों के प्रति वात्सल्य माता से भी अधिक है।" },
    nama_ids: ["n_0739", "n_0802"],
  },
  {
    id: "c_akhilaghaharitva", tier: "karunya_guna",
    en: "Akhilāghahāritva", dev: "अखिलाघहारित्व", kn: "ಅಖಿಲಾಘಹಾರಿತ್ವ", hi: "अखिलाघहारिता",
    title: { en: "Destroyer of all sins", dev: "अखिलाघ-हारित्वम्", kn: "ಅಖಿಲಾಘ-ಹಾರಿತ್ವ", hi: "अखिलाघ-हारिता" },
    note:  { en: "Mere remembrance of Hari erases all sins.", dev: "हरि-स्मरणेन सर्व-पापानां विनाशः।", kn: "ಹರಿ-ಸ್ಮರಣೆಯಿಂದ ಸಮಸ್ತ ಪಾಪಗಳ ವಿನಾಶ.", hi: "हरि-स्मरण मात्र से समस्त पापों का नाश।" },
    nama_ids: ["n_0925", "n_0992"],
  },
  {
    id: "c_pranata_rakshakatva", tier: "karunya_guna",
    en: "Praṇata-rakṣakatva", dev: "प्रणत-रक्षकत्व", kn: "ಪ್ರಣತ-ರಕ್ಷಕತ್ವ", hi: "प्रणत-रक्षकत्व",
    title: { en: "Protector of those who bow", dev: "प्रणत-रक्षकत्वम्", kn: "ಪ್ರಣತ-ರಕ್ಷಕತ್ವ", hi: "प्रणत-रक्षकता" },
    note:  { en: "Hari protects all who surrender.", dev: "हरिः सर्वान् शरणागतान् रक्षति।", kn: "ಹರಿ ಎಲ್ಲ ಶರಣಾಗತರನ್ನು ರಕ್ಷಿಸುತ್ತಾನೆ.", hi: "हरि सब शरणागतों की रक्षा करते हैं।" },
    nama_ids: ["n_0928", "n_0930"],
  },
  {
    id: "c_daridrya_bhanjana", tier: "karunya_guna",
    en: "Dāridrya-bhañjana", dev: "दारिद्र्य-भञ्जन", kn: "ದಾರಿದ್ರ್ಯ-ಭಂಜನ", hi: "दारिद्र्य-भञ्जन",
    title: { en: "Breaker of all poverty", dev: "दारिद्र्य-भञ्जनम्", kn: "ದಾರಿದ್ರ್ಯ-ಭಂಜನ", hi: "दारिद्र्य-भञ्जन" },
    note:  { en: "Hari removes material and spiritual destitution.", dev: "हरिः लौकिक-पारलौकिक-दारिद्र्यं हरति।", kn: "ಹರಿ ಲೌಕಿಕ-ಪಾರಲೌಕಿಕ ದಾರಿದ್ರ್ಯವನ್ನು ಹರಿಸುತ್ತಾನೆ.", hi: "हरि लौकिक और पारलौकिक दारिद्र्य को हरते हैं।" },
    nama_ids: ["n_0269", "n_0476"],
  },
  {
    id: "c_kripa_para_vara", tier: "karunya_guna",
    en: "Kṛpā-pārāvāra", dev: "कृपा-पारावार", kn: "ಕೃಪಾ-ಪಾರಾವಾರ", hi: "कृपा का सागर",
    title: { en: "Ocean of grace", dev: "कृपा-पारावारः", kn: "ಕೃಪಾ-ಪಾರಾವಾರ", hi: "कृपा का सागर" },
    note:  { en: "Hari's compassion is boundless as the ocean.", dev: "हरेः कृपा सागर-समाना अपार्या।", kn: "ಹರಿಯ ಕೃಪೆ ಸಾಗರ-ಸಮಾನ ಅಪಾರ.", hi: "हरि की कृपा सागर के समान अपार है।" },
    nama_ids: ["n_0461"],
  },
  {
    id: "c_bhakta_paksha_pata", tier: "karunya_guna",
    en: "Bhakta-pakṣa-pāta", dev: "भक्त-पक्ष-पात", kn: "ಭಕ್ತ-ಪಕ್ಷ-ಪಾತ", hi: "भक्त-पक्ष-पात",
    title: { en: "Bias toward the devotee's side", dev: "भक्त-पक्ष-पातः", kn: "ಭಕ್ತ-ಪಕ್ಷ-ಪಾತ", hi: "भक्त-पक्ष-पात" },
    note:  { en: "Hari sides with his devotees even against scriptural strict-justice.", dev: "हरिः भक्तानां पक्षम् आरोह्य शास्त्र-न्यायं अप्यतीत्य रक्षति।", kn: "ಹರಿ ಭಕ್ತರ ಪಕ್ಷವನ್ನು ತೆಗೆದುಕೊಂಡು ಶಾಸ್ತ್ರ-ನ್ಯಾಯವನ್ನು ಮೀರಿಯೂ ರಕ್ಷಿಸುತ್ತಾನೆ.", hi: "हरि भक्त के पक्ष में होकर शास्त्र-न्याय का अतिक्रमण करके भी रक्षा करते हैं।" },
    nama_ids: ["n_0067"],
  },
  {
    id: "c_yogeshvaratva", tier: "yoga_sthana",
    en: "Yogeśvaratva", dev: "योगेश्वरत्व", kn: "ಯೋಗೇಶ್ವರತ್ವ", hi: "योगेश्वरता",
    title: { en: "Lord of all yoga", dev: "योगेश्वरत्वम्", kn: "ಯೋಗೇಶ್ವರತ್ವ", hi: "योगेश्वरता" },
    note:  { en: "Hari is master of all yoga-paths.", dev: "हरिः सर्व-योग-मार्गाणाम् अधिपतिः।", kn: "ಹರಿ ಸಮಸ್ತ ಯೋಗ-ಮಾರ್ಗಗಳ ಅಧಿಪತಿ.", hi: "हरि समस्त योग-मार्गों के अधिपति हैं।" },
    nama_ids: ["n_0021", "n_0022"],
  },
  {
    id: "c_antaryamin", tier: "yoga_sthana",
    en: "Antaryāmin", dev: "अन्तर्यामिन्", kn: "ಅಂತರ್ಯಾಮಿನ್", hi: "अन्तर्यामी",
    title: { en: "Inner controller", dev: "अन्तर्यामिन्", kn: "ಅಂತರ್ಯಾಮಿನ್", hi: "अन्तर्यामी" },
    note:  { en: "Hari dwells within every being as inner witness and ordainer.", dev: "हरिः प्रत्येक-भूते अन्तर्यामि-रूपेण साक्षि-नियन्तृ-तया वसति।", kn: "ಹರಿ ಪ್ರತಿ ಭೂತದಲ್ಲಿ ಅಂತರ್ಯಾಮಿ-ರೂಪದಿಂದ ವಾಸಿಸುತ್ತಾನೆ.", hi: "हरि हर भूत में अन्तर्यामी रूप से बसते हैं।" },
    nama_ids: ["n_0002", "n_0016", "n_0156", "n_0245"],
  },
  {
    id: "c_sutratman", tier: "yoga_sthana",
    en: "Sūtrātman", dev: "सूत्रात्मन्", kn: "ಸೂತ್ರಾತ್ಮನ್", hi: "सूत्रात्मा",
    title: { en: "Thread-self of the cosmos", dev: "सूत्रात्मा", kn: "ಸೂತ್ರಾತ್ಮಾ", hi: "सूत्रात्मा" },
    note:  { en: "Hari pervades cosmos as the thread holding pearls.", dev: "हरिः मणि-गण-व्यापी सूत्र-इव सर्व-व्यापी।", kn: "ಹರಿ ಮಣಿ-ಗಣ-ಸೂತ್ರದಂತೆ ಸರ್ವತ್ರ ಹಬ್ಬಿರುತ್ತಾನೆ.", hi: "हरि मणियों में पिरोए सूत्र की तरह सब में व्याप्त हैं।" },
    nama_ids: ["n_0156"],
  },
  {
    id: "c_vayu_niyamaka", tier: "yoga_sthana",
    en: "Vāyu-niyāmaka", dev: "वायु-नियामक", kn: "ವಾಯು-ನಿಯಾಮಕ", hi: "वायु-नियामक",
    title: { en: "Controller of cosmic and prāṇic winds", dev: "वायु-नियामकत्वम्", kn: "ವಾಯು-ನಿಯಾಮಕತ್ವ", hi: "वायु-नियामकता" },
    note:  { en: "Hari governs the winds — both prāṇa within the body and cosmic vāyu.", dev: "हरिः वायून् नियमयति - प्राण-वायु, बाह्य-वायु च।", kn: "ಹರಿ ವಾಯುಗಳನ್ನು ನಿಯಂತ್ರಿಸುತ್ತಾನೆ.", hi: "हरि वायुओं को नियन्त्रित करते हैं।" },
    nama_ids: ["n_0292", "n_0293", "n_0335"],
  },
  {
    id: "c_hridaya_sthita", tier: "yoga_sthana",
    en: "Hṛdaya-sthita", dev: "हृदय-स्थित", kn: "ಹೃದಯ-ಸ್ಥಿತ", hi: "हृदय-स्थित",
    title: { en: "Seated in the heart", dev: "हृदय-स्थितः", kn: "ಹೃದಯ-ಸ್ಥಿತ", hi: "हृदय-स्थित" },
    note:  { en: "Hari resides in the heart-lotus of every jīva.", dev: "हरिः प्रत्येक-जीवस्य हृदय-कमले स्थितः।", kn: "ಹರಿ ಪ್ರತಿ ಜೀವದ ಹೃದಯ-ಕಮಲದಲ್ಲಿ ಸ್ಥಿತ.", hi: "हरि हर जीव के हृदय-कमल में स्थित हैं।" },
    nama_ids: ["n_0047"],
  },
  {
    id: "c_bhakta_priya", tier: "bhakta_sambandha",
    en: "Bhakta-priya", dev: "भक्त-प्रिय", kn: "ಭಕ್ತ-ಪ್ರಿಯ", hi: "भक्त-प्रिय",
    title: { en: "Dear to devotees and dear of devotees", dev: "भक्त-प्रियः", kn: "ಭಕ್ತ-ಪ್ರಿಯ", hi: "भक्त-प्रिय" },
    note:  { en: "Hari is the dearest to bhaktas and bhaktas are dearest to him.", dev: "हरिः भक्तेषु प्रियतमः, भक्ताः अपि तस्मै प्रियतमाः।", kn: "ಹರಿ ಭಕ್ತರಿಗೆ ಪ್ರಿಯತಮ, ಭಕ್ತರು ಅವನಿಗೆ ಪ್ರಿಯತಮ.", hi: "हरि भक्तों को सबसे प्रिय हैं, और भक्त उन्हें सबसे प्रिय हैं।" },
    nama_ids: ["n_0737", "n_0739", "n_0802"],
  },
  {
    id: "c_asharanya_sharana", tier: "bhakta_sambandha",
    en: "Aśaraṇya-śaraṇa", dev: "अशरण्य-शरण", kn: "ಅಶರಣ್ಯ-ಶರಣ", hi: "अशरण्य-शरण",
    title: { en: "Refuge for the refugeless", dev: "अशरण्य-शरणत्वम्", kn: "ಅಶರಣ್ಯ-ಶರಣ", hi: "अशरण्य-शरण" },
    note:  { en: "When all other refuges fail, Hari remains.", dev: "यदा सर्वे शरणाः निःशरणं याताः, हरिरेव अन्तिम-शरणम्।", kn: "ಬೇರೆಲ್ಲ ಆಶ್ರಯಗಳು ಬಿಟ್ಟರೂ ಹರಿ ಉಳಿಯುತ್ತಾನೆ.", hi: "जब सब शरण भी निःशरण हो जाते हैं, हरि ही अन्तिम शरण रहते हैं।" },
    nama_ids: ["n_0086"],
  },
  {
    id: "c_smartru_gamin", tier: "bhakta_sambandha",
    en: "Smartṛ-gāmin", dev: "स्मर्तृ-गामिन्", kn: "ಸ್ಮರ್ತೃ-ಗಾಮಿನ್", hi: "स्मर्तृ-गामी",
    title: { en: "Goes to those who remember him", dev: "स्मर्तृ-गामी", kn: "ಸ್ಮರ್ತೃ-ಗಾಮಿ", hi: "स्मर्तृ-गामी" },
    note:  { en: "Hari instantly approaches those who simply remember him.", dev: "हरिः स्मरण-मात्रेण भक्तं प्रति आगच्छति।", kn: "ಹರಿ ಕೇವಲ ಸ್ಮರಣೆಯಿಂದಲೇ ಭಕ್ತನ ಬಳಿಗೆ ಬರುತ್ತಾನೆ.", hi: "हरि स्मरण मात्र से भक्त के पास आते हैं।" },
    nama_ids: [],
  },
  {
    id: "c_bhakta_chintamani", tier: "bhakta_sambandha",
    en: "Bhakta-cintāmaṇi", dev: "भक्त-चिन्तामणि", kn: "ಭಕ್ತ-ಚಿಂತಾಮಣಿ", hi: "भक्त-चिन्तामणि",
    title: { en: "Wish-fulfilling gem for devotees", dev: "भक्त-चिन्तामणिः", kn: "ಭಕ್ತ-ಚಿಂತಾಮಣಿ", hi: "भक्त-चिन्तामणि" },
    note:  { en: "Hari fulfils every desire of his bhaktas, like the legendary wish-gem.", dev: "हरिः भक्तानां सर्व-कामना-दः चिन्तामणि-वत्।", kn: "ಹರಿ ಭಕ್ತರ ಎಲ್ಲ ಕಾಮನೆಗಳನ್ನು ಪೂರೈಸುತ್ತಾನೆ.", hi: "हरि भक्तों की सब इच्छाएँ पूरी करते हैं।" },
    nama_ids: ["n_0091", "n_0586"],
  },
  {
    id: "c_govinda_jnana_prada", tier: "bhakta_sambandha",
    en: "Govinda-jñāna-prada", dev: "गोविन्द-ज्ञान-प्रद", kn: "ಗೋವಿಂದ-ಜ್ಞಾನ-ಪ್ರದ", hi: "गोविन्द-ज्ञान-प्रद",
    title: { en: "Bestower of Govinda-knowledge", dev: "गोविन्द-ज्ञान-दः", kn: "ಗೋವಿಂದ-ಜ್ಞಾನ-ದ", hi: "गोविन्द-ज्ञान-प्रद" },
    note:  { en: "Hari grants his own knowledge to ardent bhaktas, as told in BG 10.10.", dev: "हरिः अनन्य-भक्तेभ्यः स्व-ज्ञानं ददाति।", kn: "ಹರಿ ಅನನ್ಯ-ಭಕ್ತರಿಗೆ ಸ್ವ-ಜ್ಞಾನ ಕೊಡುತ್ತಾನೆ.", hi: "हरि अनन्य भक्तों को स्व-ज्ञान देते हैं।" },
    nama_ids: ["n_0187", "n_0188"],
  },
  {
    id: "c_mukti_prada", tier: "mokshaprada",
    en: "Mukti-prada", dev: "मुक्ति-प्रद", kn: "ಮುಕ್ತಿ-ಪ್ರದ", hi: "मुक्ति-प्रद",
    title: { en: "Bestower of liberation", dev: "मुक्ति-प्रदः", kn: "ಮುಕ್ತಿ-ಪ್ರದ", hi: "मुक्ति-प्रद" },
    note:  { en: "Mokṣa is given by Hari alone.", dev: "मोक्षः केवलं हरिणैव दीयते।", kn: "ಮೋಕ್ಷ ಹರಿಯಿಂದಲೇ ದೊರೆಯುತ್ತದೆ.", hi: "मोक्ष केवल हरि से ही मिलता है।" },
    nama_ids: ["n_0013", "n_0263", "n_0451", "n_0488", "n_0685", "n_0686", "n_0982"],
  },
  {
    id: "c_salokya", tier: "mokshaprada",
    en: "Sālokya", dev: "सालोक्य", kn: "ಸಾಲೋಕ್ಯ", hi: "सालोक्य",
    title: { en: "Same-world mukti", dev: "सालोक्य-मुक्तिः", kn: "ಸಾಲೋಕ್ಯ-ಮುಕ್ತಿ", hi: "सालोक्य-मुक्ति" },
    note:  { en: "First mukti-gradation: dwelling in the same world as Hari (Vaikuṇṭha).", dev: "मुक्ति-तारतम्ये प्रथमा - हरेः लोकं (वैकुण्ठं) प्राप्तिः।", kn: "ಮುಕ್ತಿ-ತಾರತಮ್ಯದಲ್ಲಿ ಪ್ರಥಮ - ಹರಿಯ ಲೋಕ (ವೈಕುಂಠ) ಪ್ರಾಪ್ತಿ.", hi: "मुक्ति-तारतम्य की पहली श्रेणी — हरि के लोक (वैकुण्ठ) की प्राप्ति।" },
    nama_ids: ["n_0406"],
  },
  {
    id: "c_samipya", tier: "mokshaprada",
    en: "Sāmīpya", dev: "सामीप्य", kn: "ಸಾಮೀಪ್ಯ", hi: "सामीप्य",
    title: { en: "Nearness mukti", dev: "सामीप्य-मुक्तिः", kn: "ಸಾಮೀಪ್ಯ-ಮುಕ್ತಿ", hi: "सामीप्य-मुक्ति" },
    note:  { en: "Second mukti-gradation: dwelling near Hari.", dev: "मुक्ति-तारतम्ये द्वितीया - हरेः समीप-वासः।", kn: "ಮುಕ್ತಿ-ತಾರತಮ್ಯದಲ್ಲಿ ದ್ವಿತೀಯ - ಹರಿಯ ಸಮೀಪ-ವಾಸ.", hi: "मुक्ति-तारतम्य की दूसरी श्रेणी — हरि के समीप वास।" },
    nama_ids: [],
  },
  {
    id: "c_sarupya", tier: "mokshaprada",
    en: "Sārūpya", dev: "सारूप्य", kn: "ಸಾರೂಪ್ಯ", hi: "सारूप्य",
    title: { en: "Same-form mukti", dev: "सारूप्य-मुक्तिः", kn: "ಸಾರೂಪ್ಯ-ಮುಕ್ತಿ", hi: "सारूप्य-मुक्ति" },
    note:  { en: "Third mukti-gradation: assuming Hari-like form (caturbhuja).", dev: "मुक्ति-तारतम्ये तृतीया - हरि-सदृशं रूपं (चतुर्भुजं) प्राप्तिः।", kn: "ಮುಕ್ತಿ-ತಾರತಮ್ಯದಲ್ಲಿ ತೃತೀಯ - ಹರಿ-ಸದೃಶ ರೂಪ (ಚತುರ್ಭುಜ) ಪ್ರಾಪ್ತಿ.", hi: "मुक्ति-तारतम्य की तीसरी श्रेणी — हरि-सदृश रूप (चतुर्भुज) की प्राप्ति।" },
    nama_ids: [],
  },
  {
    id: "c_sayujya", tier: "mokshaprada",
    en: "Sāyujya", dev: "सायुज्य", kn: "ಸಾಯುಜ್ಯ", hi: "सायुज्य",
    title: { en: "Union mukti", dev: "सायुज्य-मुक्तिः", kn: "ಸಾಯುಜ್ಯ-ಮುಕ್ತಿ", hi: "सायुज्य-मुक्ति" },
    note:  { en: "Highest mukti-gradation: bliss-union with Hari while remaining ontologically distinct (Madhva position).", dev: "मुक्ति-तारतम्ये उत्तमा - हरिणा सह आनन्द-योगः, स्वरूपतः तु पृथक्।", kn: "ಮುಕ್ತಿ-ತಾರತಮ್ಯದ ಉತ್ತಮ - ಹರಿಯೊಡನೆ ಆನಂದ-ಯೋಗ, ಆದರೆ ಸ್ವರೂಪತಃ ಬೇರೆ.", hi: "मुक्ति-तारतम्य की उच्चतम श्रेणी — हरि के साथ आनन्द-योग, परन्तु स्वरूपतः भिन्न।" },
    nama_ids: ["n_0954"],
  },
  {
    id: "c_bhakta_kaivalya_dayaka", tier: "mokshaprada",
    en: "Bhakta-kaivalya-dāyaka", dev: "भक्त-कैवल्य-दायक", kn: "ಭಕ್ತ-ಕೈವಲ್ಯ-ದಾಯಕ", hi: "भक्त-कैवल्य-दायक",
    title: { en: "Granter of absolute liberation to devotees", dev: "भक्त-कैवल्य-दायकत्वम्", kn: "ಭಕ್ತ-ಕೈವಲ್ಯ-ದಾಯಕತ್ವ", hi: "भक्त-कैवल्य-दायकता" },
    note:  { en: "Hari grants final kaivalya to true bhaktas.", dev: "हरिः सत्य-भक्तेभ्यः अन्तिमं कैवल्यं ददाति।", kn: "ಹರಿ ಸತ್ಯ-ಭಕ್ತರಿಗೆ ಅಂತಿಮ ಕೈವಲ್ಯ ಕೊಡುತ್ತಾನೆ.", hi: "हरि सच्चे भक्तों को अन्तिम कैवल्य देते हैं।" },
    nama_ids: ["n_0263"],
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CTIERS, CONCEPTS };
}
